### ISSUE TITLE
Makefile does not provide "modules_install" function

### ISSUE THREAD

**Issue by vonfritz** [xapp-le/owl#2]
Well it builds correctly kernel and modules but it does not provide modules_install.
For my purpose I have it added to the Makefile (scripts/root.mk):

modules_install: $(K_BLD_CONFIG)
        $(Q)mkdir -p $(KERNEL_OUT_DIR)/output
        $(Q)$(MAKE) -C $(KERNEL_SRC) CROSS_COMPILE=$(CROSS_COMPILE) ARCH=$(ARCH) O=$(KERNEL_OUT_DIR) -j$(CPUS) INSTALL_MOD_PATH=output modules_install

**Comment by william-wyliang** [comment]
That's right. Previously, the procedure was only mentioned on the wiki in
the step:
http://wiki.linux-xapple.org/w/index.php/How_To_Deploy_Linaro_ALIP#Install_the_kernel_module_into_the_root-fs.
It wasn't formally added in the build script yet.

Could you send a pull request on github so that any of the maintainers can
help review and accept your contribution?

Thanks!

BRs,
William Liang

-- mail sent from my phone --
2016年1月11日 上午12:00於 "Marco Franceschetti" <notifications@github.com>寫道：

**Comment by vonfritz** [comment]
OK,
vs. master or master-new?

**Comment by william-wyliang** [comment]
I think it is master. Master-new will be an intermediate branch for merging Actions' latest release with the master branch.

**Comment by william-wyliang** [comment]
Pull request accepted and merged. (Reference: https://github.com/xapp-le/owl/pull/3) 
Thanks to Vonfritz!
